server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:192.168.100.128:8848}
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/course/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: learning-service
          uri: lb://learning-service
          predicates:
            - Path=/api/learning/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
    sentinel:
      transport:
        dashboard: ${SENTINEL_DASHBOARD:localhost:8858}

jwt:
  secret: ${JWT_SECRET:}
  ttl: 604800000

logging:
  level:
    com.learning: debug
