server:
  port: 8086

spring:
  application:
    name: learning-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.100.128}:3306/learning_learning?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:040615}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:192.168.100.128}
      port: 6379
      password: ${REDIS_PWD:040615}
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.100.128}
    port: 5672
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PWD:040615}
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    openfeign:
      client:
        config:
          course-service:
            url: http://localhost:8082
    nacos:
      discovery:
        enabled: false
        server-addr: ${NACOS_SERVER:localhost:8848}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: LearningPlatformJwtSecretKey2026!@#
  ttl: 604800000
