server:
  port: 8086

spring:
  application:
    name: learning-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.100.128}:3306/learning_learning?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST:192.168.100.128}
      port: 6379
      password: ${REDIS_PWD:}
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.100.128}
    port: 5672
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PWD:}
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER:localhost:8848}

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET:}
  ttl: 604800000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: method
