server:
  port: 8087

spring:
  application:
    name: admin-service
  profiles:
    active: local
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.100.128}
    port: 5672
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PWD:}
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    openfeign:
      client:
        config:
          course-service:
            url: http://localhost:8082
          user-service:
            url: http://localhost:8081
          order-service:
            url: http://localhost:8084
    nacos:
      discovery:
        enabled: false
        server-addr: ${NACOS_SERVER:localhost:8848}

jwt:
  secret: ${JWT_SECRET:}
  ttl: 604800000

logging:
  level:
    com.learning: debug
