server:
  port: 8087

spring:
  application:
    name: admin-service
  profiles:
    active: local
  rabbitmq:
    host: ${RABBITMQ_HOST:192.168.100.128}
    port: 5672
    username: ${RABBITMQ_USER:root}
    password: ${RABBITMQ_PWD:040615}
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${NACOS_SERVER:192.168.100.128:8848}

jwt:
  secret: ${JWT_SECRET:}
  ttl: 604800000

logging:
  level:
    com.learning: debug

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: method
